/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medieevil_201602909;

import imagenes.Casilla;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static medieevil_201602909.MedieEvil_201602909.Player1;
import static medieevil_201602909.MedieEvil_201602909.Player2;

/**
 *
 * @author edgom
 */
public class Composicion_201602909 extends javax.swing.JFrame {

    public static int Dimension;
    public static int altob=100;
    public static int anchob=100;
    public Casilla[] comp1 = new Casilla[3];
    public Casilla[] comp2 = new Casilla[3];
    
    public Composicion_201602909() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Composicion();
        this.repaint();
    }

    public void Composicion() {
        
        for (int i = 0; i < comp1.length; i++) {
            comp1[i] = new Casilla();
            comp1[i].setSize(anchob,altob);
            comp1[i].setLocation(i*100,i);
            pj1.add(comp1[i]);          
        }
        for (int i = 0; i < comp2.length; i++) {
            comp2[i] = new Casilla();
            comp2[i].setSize(anchob,altob);
            comp2[i].setLocation(i*100,i);
            pj2.add(comp2[i]);          
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nj1 = new javax.swing.JTextField();
        nj2 = new javax.swing.JTextField();
        pj1 = new javax.swing.JPanel();
        pj2 = new javax.swing.JPanel();
        btnjugar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("MedieEvil");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige el Orden de tus Personajes...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 52, 356, 34);

        jLabel2.setFont(new java.awt.Font("Colonna MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador 1:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 150, 85, 20);

        jLabel3.setFont(new java.awt.Font("Colonna MT", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jugador 2:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 150, 84, 20);
        getContentPane().add(nj1);
        nj1.setBounds(60, 190, 150, 19);
        getContentPane().add(nj2);
        nj2.setBounds(430, 190, 150, 19);

        javax.swing.GroupLayout pj1Layout = new javax.swing.GroupLayout(pj1);
        pj1.setLayout(pj1Layout);
        pj1Layout.setHorizontalGroup(
            pj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pj1Layout.setVerticalGroup(
            pj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pj1);
        pj1.setBounds(60, 250, 300, 100);

        javax.swing.GroupLayout pj2Layout = new javax.swing.GroupLayout(pj2);
        pj2.setLayout(pj2Layout);
        pj2Layout.setHorizontalGroup(
            pj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pj2Layout.setVerticalGroup(
            pj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(pj2);
        pj2.setBounds(430, 250, 300, 100);

        btnjugar.setBackground(new java.awt.Color(255, 255, 255));
        btnjugar.setFont(new java.awt.Font("Colonna MT", 0, 14)); // NOI18N
        btnjugar.setForeground(new java.awt.Color(0, 0, 0));
        btnjugar.setText("Jugar ");
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnjugar);
        btnjugar.setBounds(650, 470, 101, 57);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campodebatalla1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
    Dimension = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese las Dimensiones del Tablero", "Dimension del Tablero", INFORMATION_MESSAGE));
    JOptionPane.setDefaultLocale(null);
    if(Dimension<8)
    {
    JOptionPane.showMessageDialog(null, "El tamaño ingresado es muy pequeño \n ingrese otro tamaño e intente nuevamente.", "Error Dimension Tablero", ERROR_MESSAGE);
    }
    else if(Dimension>18)
    {
    JOptionPane.showMessageDialog(null, "El tamaño ingresado es muy grande  \n ingrese otro tamaño e intente nuevamente.", "Error Dimension Tablero", ERROR_MESSAGE);
    }
    else
    {
    Player1=nj1.getText();
    Player2=nj2.getText();   
    Game_201602909 g = new Game_201602909();
    g.setVisible(true);
    }
    }//GEN-LAST:event_btnjugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Composicion_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Composicion_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Composicion_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Composicion_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Composicion_201602909().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nj1;
    private javax.swing.JTextField nj2;
    private javax.swing.JPanel pj1;
    private javax.swing.JPanel pj2;
    // End of variables declaration//GEN-END:variables
}
