/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medieevil_201602909;

import Hilos.Up1;
import Hilos.Right1;
import Hilos.Down1;
import Hilos.Down2;
import Hilos.Left1;
import Hilos.Left2;
import Hilos.Right2;
import Hilos.Up2;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static medieevil_201602909.Composicion_201602909.Dimension;
import static medieevil_201602909.MedieEvil_201602909.Player1;
import static medieevil_201602909.MedieEvil_201602909.Player2;

/**
 *
 * @author edgom
 */
public class Game_201602909 extends javax.swing.JFrame {

   ImageIcon d1, d2, d3, d4, d5, d6,up,down,left,right;
   Icon N,D1,D2,D3,D4,D5,D6,UP,DOWN,LEFT,RIGHT; 
   public int NoDado;
   public static int Turno=5;
   public Tablero_201602909 tab;
    
    public Game_201602909() {
        initComponents();
        this.setLocationRelativeTo(null);
        lp1.setText(Player1);
        lp2.setText(Player2);
        AgregarFlechas();
        this.repaint();
    }    
    public void AgregarFlechas()
    {
    up = new ImageIcon(getClass().getResource("/imagenes/up.png"));
    down = new ImageIcon(getClass().getResource("/imagenes/down.png"));
    left = new ImageIcon(getClass().getResource("/imagenes/left.png"));
    right = new ImageIcon(getClass().getResource("/imagenes/right.png"));
    UP = new ImageIcon(up.getImage().getScaledInstance(75, 30, Image.SCALE_DEFAULT));
    DOWN = new ImageIcon(down.getImage().getScaledInstance(75, 30, Image.SCALE_DEFAULT));
    LEFT = new ImageIcon(left.getImage().getScaledInstance(75, 30, Image.SCALE_DEFAULT));
    RIGHT = new ImageIcon(right.getImage().getScaledInstance(75, 30, Image.SCALE_DEFAULT));
    btnup.setIcon(UP);
    btndown.setIcon(DOWN);
    btnleft.setIcon(LEFT);
    btnright.setIcon(RIGHT);
    tab = new Tablero_201602909(Dimension,pj);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pj = new javax.swing.JPanel();
        btnup = new javax.swing.JButton();
        btnleft = new javax.swing.JButton();
        btndown = new javax.swing.JButton();
        btnright = new javax.swing.JButton();
        lp1 = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();
        btndado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("MedieEvil");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout pjLayout = new javax.swing.GroupLayout(pj);
        pj.setLayout(pjLayout);
        pjLayout.setHorizontalGroup(
            pjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        pjLayout.setVerticalGroup(
            pjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(pj);
        pj.setBounds(34, 41, 500, 500);

        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });
        getContentPane().add(btnup);
        btnup.setBounds(580, 330, 75, 30);

        btnleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleftActionPerformed(evt);
            }
        });
        getContentPane().add(btnleft);
        btnleft.setBounds(580, 380, 75, 30);

        btndown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndownActionPerformed(evt);
            }
        });
        getContentPane().add(btndown);
        btndown.setBounds(670, 330, 75, 30);

        btnright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrightActionPerformed(evt);
            }
        });
        getContentPane().add(btnright);
        btnright.setBounds(670, 380, 75, 30);

        lp1.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lp1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lp1);
        lp1.setBounds(584, 27, 161, 39);

        lp2.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lp2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lp2);
        lp2.setBounds(584, 183, 161, 37);

        btndado.setPreferredSize(new java.awt.Dimension(100, 100));
        btndado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndadoActionPerformed(evt);
            }
        });
        getContentPane().add(btndado);
        btndado.setBounds(610, 440, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campo_de_batalla_naruto_shippuden_by_lwisf3rxd-d62dfla.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndadoActionPerformed
        int no = (int) (Math.random() * 6) + 1;
        d1 = new ImageIcon(getClass().getResource("/imagenes/d1.png"));
        d2 = new ImageIcon(getClass().getResource("/imagenes/d2.png"));
        d3 = new ImageIcon(getClass().getResource("/imagenes/d3.png"));
        d4 = new ImageIcon(getClass().getResource("/imagenes/d4.png"));
        d5 = new ImageIcon(getClass().getResource("/imagenes/d5.png"));
        d6 = new ImageIcon(getClass().getResource("/imagenes/d6.png"));
        D1 = new ImageIcon(d1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D2 = new ImageIcon(d2.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D3 = new ImageIcon(d3.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D4 = new ImageIcon(d4.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D5 = new ImageIcon(d5.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D6 = new ImageIcon(d6.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));

        switch (no) {
            case 1:
                btndado.setIcon(D1);
                NoDado = no;
                break;
            case 2:
                btndado.setIcon(D2);
                NoDado = no;
                break;
            case 3:
                btndado.setIcon(D3);
                NoDado = no;
                break;
            case 4:
                btndado.setIcon(D4);
                NoDado = no;
                break;
            case 5:
                btndado.setIcon(D5);
                NoDado = no;
                break;
            case 6:
                btndado.setIcon(D6);
                NoDado = no;
                break;
        }
    }//GEN-LAST:event_btndadoActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
//    Up1 u1 = new Up1(NoDado,tab);
//    u1.start();

        Up2 u2 = new Up2(NoDado, tab);
        u2.start();
    }//GEN-LAST:event_btnupActionPerformed

    private void btndownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndownActionPerformed
//    Down1 dn1 = new Down1(NoDado,tab);
//    dn1.start();

        Down2 dn2 = new Down2(NoDado, tab);
        dn2.start();
    }//GEN-LAST:event_btndownActionPerformed

    private void btnleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleftActionPerformed
//    Left1 l1 = new Left1(NoDado,tab);
//    l1.start();

        Left2 l2 = new Left2(NoDado, tab);
        l2.start();
    }//GEN-LAST:event_btnleftActionPerformed

    private void btnrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrightActionPerformed
// Right1 r1 = new Right1(NoDado,tab);
//  r1.start();

        Right2 r2 = new Right2(NoDado, tab);
        r2.start();
    }//GEN-LAST:event_btnrightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_201602909().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndado;
    private javax.swing.JButton btndown;
    private javax.swing.JButton btnleft;
    private javax.swing.JButton btnright;
    private javax.swing.JButton btnup;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lp1;
    public static javax.swing.JLabel lp2;
    private javax.swing.JPanel pj;
    // End of variables declaration//GEN-END:variables
}
