/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medieevil_201602909;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import static medieevil_201602909.MedieEvil_201602909.Player1;
import static medieevil_201602909.MedieEvil_201602909.Player2;

/**
 *
 * @author edgom
 */
public class Game_201602909 extends javax.swing.JFrame {

   ImageIcon d1, d2, d3, d4, d5, d6;
   Icon N,D1,D2,D3,D4,D5,D6; 
   public int NoDado;
    
    public Game_201602909() {
        initComponents();
        this.setLocationRelativeTo(null);
        lp1.setText(Player1);
        lp2.setText(Player2);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lp1 = new javax.swing.JLabel();
        lp2 = new javax.swing.JLabel();
        btndado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("MedieEvil");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(34, 41, 500, 500);
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 330, 75, 30);
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 380, 75, 30);
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 330, 75, 30);
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 380, 75, 30);

        lp1.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lp1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lp1);
        lp1.setBounds(584, 27, 161, 39);

        lp2.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        lp2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lp2);
        lp2.setBounds(584, 183, 161, 37);

        btndado.setPreferredSize(new java.awt.Dimension(100, 100));
        btndado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndadoActionPerformed(evt);
            }
        });
        getContentPane().add(btndado);
        btndado.setBounds(610, 440, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campo_de_batalla_naruto_shippuden_by_lwisf3rxd-d62dfla.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndadoActionPerformed
        int no = (int) (Math.random() * 6) + 1;
        d1 = new ImageIcon(getClass().getResource("/imagenes/d1.png"));
        d2 = new ImageIcon(getClass().getResource("/imagenes/d2.png"));
        d3 = new ImageIcon(getClass().getResource("/imagenes/d3.png"));
        d4 = new ImageIcon(getClass().getResource("/imagenes/d4.png"));
        d5 = new ImageIcon(getClass().getResource("/imagenes/d5.png"));
        d6 = new ImageIcon(getClass().getResource("/imagenes/d6.png"));
        D1 = new ImageIcon(d1.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D2 = new ImageIcon(d2.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D3 = new ImageIcon(d3.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D4 = new ImageIcon(d4.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D5 = new ImageIcon(d5.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        D6 = new ImageIcon(d6.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));

        switch (no) {
            case 1:
                btndado.setIcon(D1);
                NoDado = no;
                break;
            case 2:
                btndado.setIcon(D2);
                NoDado = no;
                break;
            case 3:
                btndado.setIcon(D3);
                NoDado = no;
                break;
            case 4:
                btndado.setIcon(D4);
                NoDado = no;
                break;
            case 5:
                btndado.setIcon(D5);
                NoDado = no;
                break;
            case 6:
                btndado.setIcon(D6);
                NoDado = no;
                break;
        }
    }//GEN-LAST:event_btndadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game_201602909().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lp1;
    private javax.swing.JLabel lp2;
    // End of variables declaration//GEN-END:variables
}
