/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medieevil_201602909;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author edgom
 */
public class MejoresScores_201602909 extends javax.swing.JFrame {

    private File fichero;
    private javax.swing.JFileChooser fileCh;
    public static String linea;

    public MejoresScores_201602909() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtwinners.setLineWrap(true);
        fileCh = new javax.swing.JFileChooser();
    }

    private String AbrirArchivo() {
        String cadena = "";
        int seleccion = fileCh.showDialog(this, "Seleccionar archivo");
        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            fichero = fileCh.getSelectedFile();
            cadena = fichero.getAbsolutePath();

        }
        return cadena;
    }

    private void AgregarArchivo(String ruta) {
        FileReader fr = null;
        String cadena = "";

        try {
            File archivo = new File(ruta);
            fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            String line;
            int z = 1;
            while ((line = br.readLine()) != null) {
                txtwinners.setText(txtwinners.getText() + line + "\n");

            }
        } catch (IOException e) {
        } finally {
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (IOException e2) {
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtwinners = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnwinners = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("MedieEvil");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        txtwinners.setColumns(20);
        txtwinners.setRows(5);
        jScrollPane1.setViewportView(txtwinners);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 685, 380);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mejores Jugadores:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 30, 215, 57);

        btnwinners.setBackground(new java.awt.Color(255, 255, 255));
        btnwinners.setFont(new java.awt.Font("Colonna MT", 0, 18)); // NOI18N
        btnwinners.setForeground(new java.awt.Color(0, 0, 0));
        btnwinners.setText("Ver Ganadores");
        btnwinners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwinnersActionPerformed(evt);
            }
        });
        getContentPane().add(btnwinners);
        btnwinners.setBounds(60, 110, 205, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campodebatalla1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnwinnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwinnersActionPerformed
        try {
            AgregarArchivo(AbrirArchivo());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnwinnersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MejoresScores_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MejoresScores_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MejoresScores_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MejoresScores_201602909.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MejoresScores_201602909().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnwinners;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtwinners;
    // End of variables declaration//GEN-END:variables
}
